name: Java Code Review with Gradle + GitHub API Comments

on:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Checkstyle and PMD
        run: ./gradlew checkstyleMain pmdMain

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/main.html

      - name: Install Python dependencies
        run: pip install requests

      - name: Post comments for violations
        run: python scripts/comment_on_violations.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
