name: Java Code Review with Gradle + GitHub API Comments

on:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Checkstyle and PMD (continue on violations)
        run: |
          ./gradlew checkstyleMain pmdMain || true

      # ✅ Upload Checkstyle Reports (HTML + XML)
      - name: Upload Checkstyle HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-html
          path: build/reports/checkstyle/main.html

      - name: Upload Checkstyle XML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-xml
          path: build/reports/checkstyle/main.xml

      # ✅ Upload PMD Reports (HTML + XML)
      - name: Upload PMD HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-html
          path: build/reports/pmd/main.html

      - name: Upload PMD XML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-xml
          path: build/reports/pmd/main.xml

      - name: Install Python dependencies
        run: pip install requests

      - name: Test GitHub API access
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.CDR1_TKN }}

      - name: Run test comment script
        run: python scripts/test_post_comment.py
        env:
            REPO: ${{ github.repository }}
            COMMIT_SHA: ${{ github.sha }}
            GITHUB_TOKEN: ${{ secrets.CDR1_TKN }} # or use secrets.GITHUB_TOKEN for internal commits


      - name: Post comments for violations
        run: python scripts/comment_on_violations.py
        env:
          GITHUB_TOKEN : ${{ secrets.CDR1_TKN }}
          COMMIT_SHA: ${{ github.sha }}
          REPO: ${{ github.repository }}
